### PR TITLE
fix(build): gradlew failed on gradle 7.x

### PR DESCRIPTION
**Pull request by Thearas**
Signed-off-by: Thearas <thearas850@gmail.com>

I follow the document but meet some errors on `./gradlew pz`, same as #75. The gradle v5.x is too old, I don't think there're many people using it, so I make `./gradlew pz` available on gradle 7.x.

PTAL @sing1ee

### CODE REVIEW

**Comment by zhishengzhang** [comment]
I make ./gradle pz unavailable on gradle 7.x，the error info
`* What went wrong:
A problem occurred evaluating root project 'elasticsearch-jieba-plugin'.
> Could not get unknown property 'runtime' for configuration ':distJars' of type org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
`

**Comment by Thearas** [comment]
Thank for your report @zhishengzhang.
It seems that the submodule `jieba-analysis` does not point the latest commit. Please try:

```sh
cd jieba-analysis
git pull origin master
cd -
gradle wrapper
./gradlew pz
```

And see if it does work.

**Comment by zhishengzhang** [comment]
> ```shell
> git pull origin master
> ```

$ gradle pz

FAILURE: Build failed with an exception.

* What went wrong:
Task 'pz' not found in project ':jieba-analysis'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by Thearas** [comment]
> ```shell
> ./gradlew pz
> ```

What about `gradle pz`? `gradlew` -> `gradle` 😂

**Comment by zhishengzhang** [comment]
> ```shell
> ./gradlew pz
> ```

$ ./gradlew clean pz

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all task dependencies for configuration ':compileClasspath'.
   > Could not resolve project :jieba-analysis.
     Required by:
         project :
      > No matching configuration of project :jieba-analysis was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - None of the consumable configurations have attributes.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s

**Comment by Thearas** [comment]
@zhishengzhang What's the output about `gradle pz`? The log you show above is from `./gradlew clean pz`.

**Comment by zhishengzhang** [comment]
> @zhishengzhang What's the output about `gradle pz`? The log you show above is from `./gradlew clean pz`.

https://github.com/sing1ee/elasticsearch-jieba-plugin/pull/83#issuecomment-1016201744

**Comment by Thearas** [comment]
I was not able to reproduce the error.😂
BTW, Have you run `git submodule update --init --recursive` to clone the submodule `jieba-analysis`?  @zhishengzhang

**Comment by zhishengzhang** [comment]
> ```shell
> git pull origin master
> ```
retry "gradlew pz" is avaliable；THX

Build failed reason is 
"fatal: unable to update url base from redirection:
  asked for: https://github.com/sing1ee/jieba-analysis.git/info/refs?service=git                                                                                                                                  -upload-pack
   redirect: http://1.1.1.2/disable/disable.htm?url_type=%E7%BD%91%E7%BB%9C%E5%A                                                                                                                                  D%98%E5%82%A8/%47%69%74%48%75%62%E5%AE%A2%E6%88%B7%E7%AB%AF&plc_name=%E7%A6%81%E                                                                                                                                  6%AD%A2%E5%B8%B8%E7%94%A8%E4%BB%A3%E7%A0%81%E6%89%98%E7%AE%A1%E7%BD%91%E7%AB%99%                                                                                                                                  E4%B8%8A%E4%BC%A0%E4%BB%A3%E7%A0%81"
access github with VPN

**Pull request merged**
